pump:
  pump-interval: 10s # 数据采集（pump）间隔，默认 10s

http:
  addr: 0.0.0.0:8020 # 默认 0.0.0.0:8000
  mode: release # release, debug, test，默认 release
  healthz: true # 是否开启健康检查, router: /healthz，默认 true
  ping-timeout: 10s # http 服务启动后，自检超时时间，默认 10s
  middlewares:
    - recovery
    - logger

redis:
  addrs:
    - "localhost:6379"
  password: "774411"
  database: 0

mongo:
  uri: "mongodb://localhost:27017" # 默认 mongodb://localhost:27017
  database: iam_authz_audit
  username: che
  password: "774411"
  max-pool-size: 200 # 默认 100

# https://pkg.go.dev/go.uber.org/zap#hdr-Configuring_Zap
log:
  development: true
  disable-caller: true
