pump:
  pump-interval: 10s # 数据抽运（pump）间隔，默认 10s
  omit-details: true # 忽略详细数据，默认 true

http:
  addr: 0.0.0.0:8020 # 默认 0.0.0.0:8000
  mode: release # release, debug, test，默认 release
  healthz: true # 是否开启健康检查, router: /healthz，默认 true
  ping-timeout: 10s # http 服务启动后，自检超时时间，默认 10s

redis:
  addrs:
    - "127.0.0.1:6379" # 1个addr为单节点模式，多个addrs为cluster模式
  password: "774411"
  database: 0

mongo:
  uri: "mongodb://che:'774411'@127.0.0.1:27017/iam_authz_audit"
  max-pool-size: 200 # 默认 100

# https://pkg.go.dev/go.uber.org/zap#hdr-Configuring_Zap
log:
  development: true
  disable-caller: true
